# yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
#
# Windows:
# winget install Task.Task
#
# Linux:
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
# echo 'command -v task >/dev/null || export PATH="$PATH:$HOME/.local/bin"' >> ~/.profile
# source ~/.profile
#
# macOS:
# brew install go-task/tap/go-task
---
version: "3"

vars:
  PROJECT_NAME: godog
  MODULE_NAME:
    sh: go mod edit -json | jq .Module.Path -r


tasks:
  # ----------------------
  # Development
  # ----------------------
  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./animals -timeout 30s -coverprofile=coverage.out github.com/hattan/godog/animals

  test:cover:
    desc: Run unit tests and show code coverage
    cmds:
      - |
        go test ./animals -timeout 30s -coverprofile=coverage.out github.com/hattan/godog/animals
        go tool cover -html coverage.out -o coverage.html
